name: day11
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - gdal
  - jupyter
  - notebook
  - jupyterlab
  - scipy
  - numba
  - libgdal
